easy_admin:
    site_name: 'Europrofili s.p.a.'

    entities:
        # List the entity class name you want to manage
        Famiglia:
            class:  App\Entity\Famiglia
            new:
                fields:
                    - id
                    - descrizione
                    - articoli
        Articolo:
            class:  App\Entity\Articolo
        Listino:
            class:  App\Entity\Listino
        Classe:
            class:  App\Entity\Classe

framework:
    translator: { fallbacks: [ "en" ] }
